// svelte-kit-app/src/routes/search/+page.svelte
<script lang="ts">
	import PopularCombinations from '$lib/components/PopularCombinations.svelte';
	import AirportCard from '$lib/components/AirportCard.svelte';
	import ViewToggle from '$lib/components/ViewToggle.svelte';
	import { Card } from '$lib/components/ui/card';
	import { useSearchQueryParams } from '$lib/hooks/use-query-params.svelte';
	import { Plane, AlertCircle } from '@lucide/svelte';
	import { browser } from '$app/environment';
	import SearchResult from './SearchResult.svelte';

	const { data } = $props();

	const searchParams = useSearchQueryParams();
	const IATA_CODES = $derived(data.IATA_CODES);
</script>

<svelte:head>
	<title>FlightAnchor Search - Multi-City Flight Routes | Meeting Point Finder</title>
	<meta
		name="description"
		content="Search and compare flight routes from multiple airports to find your perfect meeting destination. FlightAnchor simplifies group travel planning."
	/>
</svelte:head>

<div class="min-h-screen bg-background">
	<div class="px-4 py-8">
		<!-- Header -->
		<div class="mb-8 text-center">
			<h1 class="text-3xl font-bold tracking-tight md:text-4xl">Find Your Meeting Point</h1>
			<p class="mt-2 text-lg text-muted-foreground">
				Compare flight routes from multiple airports to discover the perfect destination
			</p>
		</div>

		<div>
			{#if IATA_CODES.length < 2}
				<!-- Empty State -->
				<Card class="p-12 text-center">
					<Plane class="mx-auto mb-4 size-16 text-muted-foreground" />
					<h2 class="mb-2 text-2xl font-semibold">Start Your Search</h2>
					<p class="mb-6 text-muted-foreground">
						Add at least 2 airports to find meeting destinations
					</p>
					<PopularCombinations />
				</Card>
			{:else}
				<SearchResult />
				<!-- Results Header -->
				<div class="mb-6 flex items-center justify-between">
					<div>
						<h2 class="text-2xl font-semibold">
							Meeting Points from {IATA_CODES.join(' + ')}
						</h2>
						<p class="text-muted-foreground">
							Common destinations reachable from all selected airports
						</p>
					</div>
					<ViewToggle />
				</div>

				<!-- Results Content -->
				<svelte:boundary>
					<!-- {@const result = await useFlightRouteQuery(IATA_CODES)} -->
					{@const result = data}

					{#if result.routes.length == 0}
						No results found
					{:else if searchParams.activeView === 'grid'}
						<!-- Grid View -->
						<div class="grid gap-6 md:grid-cols-2">
							{#each result.routes as route}
								<AirportCard {route} />
							{/each}
						</div>
					{:else if searchParams.activeView == 'map'}
						<!-- Map View -->
						<Card class="overflow-hidden p-0">
							<div class="h-[600px]">
								{#if browser}
									{@const formattedAirports = result.routes.map((route) => ({
										iata_code: route.destination_airport.iata_code,
										name: route.destination_airport.name,
										city_name: route.destination_airport.city_name,
										country_name: route.destination_airport.country_name,
										latitude: route.destination_airport.latitude,
										longitude: route.destination_airport.longitude
									}))}
									{#await import('$lib/components/AirportsMap.svelte') then { default: AirportsMap }}
										<AirportsMap airports={formattedAirports} />
									{/await}
								{/if}
							</div>
						</Card>
					{/if}
					{#snippet pending()}
						<div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
							{#each { length: 6 } as _}
								<Card class="animate-pulse p-6">
									<div class="mb-4 h-4 w-3/4 rounded bg-muted"></div>
									<div class="mb-2 h-3 w-1/2 rounded bg-muted"></div>
									<div class="h-3 w-2/3 rounded bg-muted"></div>
								</Card>
							{/each}
						</div>
					{/snippet}

					{#snippet failed(err)}
						<Card class="p-12 text-center">
							{err}
							<AlertCircle class="mx-auto mb-4 size-16 text-destructive" />
							<h2 class="mb-2 text-2xl font-semibold">Search Error</h2>
							<p class="text-muted-foreground">
								There was an error searching for flight routes. Please try again.
							</p>
						</Card>
					{/snippet}
				</svelte:boundary>
			{/if}
		</div>
	</div>
</div>

// react-router-app/app/routes/search.tsx
import type { Route } from "./+types/search";

import { flightRouteService } from "@travel-anchor/data-access-layer";
import React from "react";
import { Await } from "react-router";

import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import { Separator } from "~/components/ui/separator";
import { Skeleton } from "~/components/ui/skeleton";
import {
	DestinationListView,
	getIATACodesFromSearchParams,
	OriginCitiesFilter,
	useAirportSearchParamsState,
	ViewToggle,
} from "~/features/airport-search";
import { AirportsMap } from "~/features/airport-search/components/AirportsMap.client";
import { isBrowser } from "~/lib/utils";

export async function loader({ request }: Route.LoaderArgs) {
	const requestURLObject = new URL(request.url);
	const iataCodes = getIATACodesFromSearchParams(requestURLObject.searchParams);

	if (iataCodes.length < 2) {
		return { routes: [] };
	}

	const routes = new Promise<
		Awaited<ReturnType<typeof flightRouteService.getAirportRoutesByIATA>>
	>((res) => res(flightRouteService.getAirportRoutesByIATA(iataCodes)));

	return {
		routes,
	};
}

export type SearchPageLoaderResponse = Awaited<
	ReturnType<typeof flightRouteService.getAirportRoutesByIATA>
>;

export function meta() {
	return [
		{ title: "Mutual Flight Destinations - Travel Anchor" },
		{
			name: "description",
			content: "Find mutual direct-flight destinations for your group travel",
		},
	];
}

export default function SearchPage({ loaderData }: Route.ComponentProps) {
	const { activeView } = useAirportSearchParamsState();

	return (
		<div className="min-h-screen bg-background">
			<div className="container mx-auto px-4 py-8">
				<div className="mb-8">
					<h1 className="text-3xl font-bold font-sans tracking-tight text-foreground mb-2">
						{/* {loaderData.routes.length} */}
						Mutual Flight Destinations
					</h1>
					<OriginCitiesFilter />
					<ViewToggle />
				</div>
				<React.Suspense fallback={<LoadingSkeleton />}>
					<Await resolve={loaderData.routes} errorElement={<ErrorElement />}>
						{(routes) => {
							if (activeView == "grid") {
								return <DestinationListView routes={routes} />;
							}
							if (!isBrowser) {
								return null;
							}
							return (
								<AirportsMap
									airports={routes.map(
										({ destination_airport }) => destination_airport,
									)}
								/>
							);
						}}
					</Await>
				</React.Suspense>
			</div>
		</div>
	);
}

function LoadingSkeleton() {
	const { activeView, iataCodes } = useAirportSearchParamsState();
	if (activeView === "map") {
		return (
			<div className="space-y-4">
				<div className="text-center text-muted-foreground">
					Loading map destinations...
				</div>
				<Skeleton className="h-96 w-full rounded-lg" />
			</div>
		);
	}

	return (
		<div className="space-y-4">
			<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
				{Array.from({ length: 4 }).map((_, idx) => (
					// biome-ignore lint/suspicious/noArrayIndexKey: no other option
					<Card key={idx} className="w-full">
						<CardHeader>
							<CardTitle className="flex items-center justify-between">
								<div className="space-y-2 w-full">
									<Skeleton variant="grid" className="h-6 w-1/2" />
									<Skeleton variant="grid" className="h-4 w-1/4" />
								</div>
							</CardTitle>
						</CardHeader>
						<Separator />
						<CardContent className="space-y-4 mt-4">
							<div className="space-y-2">
								{iataCodes.map((code, index) => (
									<div key={code}>
										<Skeleton variant="grid" className="h-28 w-full" />
										{index < iataCodes.length - 1 && (
											<Separator className="my-3" />
										)}
									</div>
								))}
							</div>
						</CardContent>
					</Card>
				))}
			</div>
		</div>
	);
}

function ErrorElement() {
	return <div>Error loading routes</div>;
}
