// svelte-kit-app/src/routes/search/+page.svelte
<script lang="ts">
	import SearchSidebar from '$lib/components/SearchSidebar.svelte';
	import AirportCard from '$lib/components/AirportCard.svelte';
	import ViewToggle from '$lib/components/ViewToggle.svelte';
	import { Card } from '$lib/components/ui/card';
	import { useSearchQueryParams } from '$lib/hooks/use-query-params.svelte';
	import { Plane, AlertCircle } from '@lucide/svelte';
	import { browser } from '$app/environment';
	import * as Sidebar from '$lib/components/ui/sidebar';

	const { data } = $props();

	const searchParams = useSearchQueryParams();
	const IATA_CODES = $derived(data.IATA_CODES);
</script>

<svelte:head>
	<title>FlightAnchor Search - Multi-City Flight Routes | Meeting Point Finder</title>
	<meta
		name="description"
		content="Search and compare flight routes from multiple airports to find your perfect meeting destination. FlightAnchor simplifies group travel planning."
	/>
</svelte:head>

<div class="flex min-h-screen">
	<SearchSidebar />

	<Sidebar.Inset>
		<div class="px-4 py-8">
			<!-- Header with Sidebar Trigger -->
			<div class="mb-8 flex items-center gap-4">
				<Sidebar.Trigger />

				<div class="w-full">
					{#if IATA_CODES.length > 2}
						<!-- Results Header -->
						<div class="flex items-center justify-between">
							<div>
								<h1 class="text-2xl font-semibold">
									Meeting Points from {IATA_CODES.join(' + ')}
								</h1>
								<p class="text-muted-foreground">
									Common destinations reachable from all selected airports
								</p>
							</div>
							<ViewToggle />
						</div>
					{:else}
						<h1 class="text-2xl font-semibold tracking-tight">Find Your Meeting Point</h1>
						<p class="mt-2 text-lg text-muted-foreground">
							Compare flight routes from multiple airports to discover the perfect destination
						</p>
					{/if}
				</div>
			</div>

			{#if IATA_CODES.length < 2}
				<!-- Empty State -->
				<Card class="p-12 text-center">
					<Plane class="mx-auto mb-4 size-16 text-muted-foreground" />
					<h2 class="mb-2 text-2xl font-semibold">Start Your Search</h2>
					<p class="mb-6 text-muted-foreground">
						Use the sidebar to add at least 2 airports to find meeting destinations
					</p>
				</Card>
			{:else}
				<!-- Results Content -->
				<svelte:boundary>
					<!-- {@const result = await useFlightRouteQuery(IATA_CODES)} -->
					{@const result = data}

					{#if result.routes.length == 0}
						<Card class="p-12 text-center">
							<Plane class="mx-auto mb-4 size-16 text-muted-foreground" />
							<h2 class="mb-2 text-2xl font-semibold">No Results Found</h2>
							<p class="text-muted-foreground">
								No common destinations found for the selected airports
							</p>
						</Card>
					{:else if searchParams.activeView === 'grid'}
						<!-- Grid View -->
						<div class="grid gap-6">
							{#each result.routes as route}
								<AirportCard {route} />
							{/each}
						</div>
					{:else if searchParams.activeView == 'map'}
						<!-- Map View -->
						<Card class="overflow-hidden p-0">
							<div class="h-[600px]">
								{#if browser}
									{@const formattedAirports = result.routes.map((route) => ({
										iata_code: route.destination_airport.iata_code,
										name: route.destination_airport.name,
										city_name: route.destination_airport.city_name,
										country_name: route.destination_airport.country_name,
										latitude: route.destination_airport.latitude,
										longitude: route.destination_airport.longitude
									}))}
									{#await import('$lib/components/AirportsMap.svelte') then { default: AirportsMap }}
										<AirportsMap airports={formattedAirports} />
									{/await}
								{/if}
							</div>
						</Card>
					{/if}
					{#snippet pending()}
						<div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
							{#each { length: 6 } as _}
								<Card class="animate-pulse p-6">
									<div class="mb-4 h-4 w-3/4 rounded bg-muted"></div>
									<div class="mb-2 h-3 w-1/2 rounded bg-muted"></div>
									<div class="h-3 w-2/3 rounded bg-muted"></div>
								</Card>
							{/each}
						</div>
					{/snippet}

					{#snippet failed(err)}
						<Card class="p-12 text-center">
							<AlertCircle class="mx-auto mb-4 size-16 text-destructive" />
							<h2 class="mb-2 text-2xl font-semibold">Search Error</h2>
							<p class="text-muted-foreground">
								There was an error searching for flight routes. Please try again.
							</p>
						</Card>
					{/snippet}
				</svelte:boundary>
			{/if}
		</div>
	</Sidebar.Inset>
</div>

// nuxt-app/app/pages/search.vue
<script setup lang="ts">
import { AirportCard, AirportsMap, SearchSideBar } from "#components";
import { useFlightRouteQuery } from "~/composables/use-queries";
import { useSearchQueryParams } from "~/composables/use-query-params";

useSeoMeta({
  title:
    "FlightAnchor Search - Multi-City Flight Routes | Meeting Point Finder",
  description:
    "Search and compare flight routes from multiple airports to find your perfect meeting destination. FlightAnchor simplifies group travel planning.",
});

const { activeView, iataCodes } = useSearchQueryParams();
const iataQuery = useFlightRouteQuery();
</script>

<template>
  <UDashboardGroup>
    <SearchSideBar />

    <!-- Main Content Panel -->
    <UDashboardPanel id="search">
      <template #header>
        <UDashboardNavbar>
          <template #left>
            <div class="flex items-center gap-4">
              <h1 class="text-lg font-semibold">
                {{ iataQuery.data.value?.routes?.length }} Meeting Points
                <span
                  v-if="iataCodes.length > 0"
                  class="text-toned font-normal"
                >
                  from {{ iataCodes.join(", ") }}
                </span>
              </h1>
            </div>
          </template>
        </UDashboardNavbar>
      </template>

      <template #body>
        <UContainer>
          <div class="flex flex-col gap-y-5 py-10">
            <template
              v-if="
                iataQuery.data.value && iataQuery.data.value.routes.length > 0
              "
            >
              <div
                v-if="activeView === 'grid'"
                class="grid grid-cols-1 md:grid-cols-2 gap-10"
              >
                <AirportCard
                  v-for="route in iataQuery.data.value.routes"
                  :key="route.destination_airport.iata_code"
                  :route="route"
                />
              </div>
              <div
                v-else-if="activeView === 'map'"
                class="h-[400px] md:h-[600px]"
              >
                <ClientOnly>
                  <AirportsMap
                    :airports="
                      iataQuery.data.value.routes.map(
                        (route) => route.destination_airport
                      )
                    "
                  />
                  <template #fallback>
                    <USkeleton class="size-full" />
                  </template>
                </ClientOnly>
              </div>
            </template>
            <template v-else-if="iataQuery.status.value == 'pending'">
              <div class="text-center">
                <div class="flex justify-center mb-4">
                  <UIcon
                    name="lucide:plane"
                    class="w-12 h-12 text-primary-500 animate-pulse"
                  />
                </div>
                <h3 class="text-xl font-semibold mb-2">
                  Finding your perfect meeting spots...
                </h3>
                <p class="text-muted-foreground">
                  Searching for destinations with direct flights from all your
                  selected airports
                </p>
              </div>
            </template>
            <template v-else>
              <div class="text-center py-12">
                <UIcon
                  name="lucide:search-x"
                  class="w-16 h-16 text-muted-foreground mb-4"
                />
                <h3 class="text-2xl font-semibold mb-2">
                  No common destinations found
                </h3>
                <p class="text-muted-foreground mb-6 max-w-md mx-auto">
                  We couldn't find any destinations with direct flights from all
                  your selected airports. Try adding more airports or checking
                  different combinations.
                </p>
                <UButton
                  label="Try Popular Combinations"
                  variant="outline"
                  @click="navigateTo('/')"
                />
              </div>
            </template>
          </div>
        </UContainer>
      </template>
    </UDashboardPanel>
  </UDashboardGroup>
</template>
